### ISSUE TITLE
Mismatch between source code and wiki on package installer

### ISSUE THREAD

**Issue by yrezgui** [KimWooHyun/vue-lunar-calendar#11]
Hi!

In the repository, there is a `yarn.lock` file and the instructions to contribute are mentioning Yarn but in the README, the instructions are using NPM.

Isn't it better to stick with just one of them or document for both of them?

**Comment by yrezgui** [comment]
I created a PR here: https://github.com/KimWooHyun/vue-lunar-calendar/pull/12

**Comment by KimWooHyun** [comment]
Hi.

First, Thank you for your PR.
I've seen a lot of things I missed.
Thank you for your good feedback.
I'll merge it.

Thanks.

**Comment by KimWooHyun** [comment]
I published it to npm.
Merci!
