### ISSUE TITLE
Css Problem in calendar

### ISSUE THREAD

**Issue by techguydev** [KimWooHyun/vue-lunar-calendar#14]
Hi, I added this calendar to a Laravel app and  the days in the top are bigger than they shoulded be, also the cells of the days which make it look not so nice.

Any though on how I could fix it?

Thanks

**Comment by KimWooHyun** [comment]
Hello.
Thank you for using the library.
I will add the ability to change the font size and the color of the selected cell in the future.
However, if you need to change quickly, there is a way to modify global css. Using the important.
From the file to which you imported the library.
Thanks.

**Comment by techguydev** [comment]
Hello Kim, 

Thank you for sharing such a nice calendar.

I tried to update your source file and it worked, the problem is that as I work with another team members  when they compile their  work it looks different since do not have the modifications in your source files.

**Comment by KimWooHyun** [comment]
I decided to remove the scoped in the style tag.
However, it seems to take some time because I have to work on the side effect when removing it.
I will be working on this weekend.
Removing scoped seems to increase the degree of style freedom. Will it help with current issues?
