### ISSUE TITLE
Show the day with differents backgroud colors according to variable

### ISSUE THREAD

**Issue by techguydev** [KimWooHyun/vue-lunar-calendar#15]
Hi Kim, 

Thanks again for such a nice component.

I was wondering if it is possible to change the color of  each day according with a variable I can retrieve.

I want to use this component for a booking application, so it would be great to be able to  show the clients when each day is available  at first sight

Thanks

**Comment by KimWooHyun** [comment]
Sorry. I've missed this issue. 😢 

I confirmed the issue and uploaded PR. #29
It's a lot late, but can you check it out?

Thanks for your interest this repo.
