### ISSUE TITLE
can you add a new function，'jump back today'

### ISSUE THREAD

**Issue by agreadname** [KimWooHyun/vue-lunar-calendar#24]
I found the props of 'defaultDate' that can't come true this function
I did some manipulation by your dome
1. input "2018-12-24" 
2. click search button  
3. click other date  
4. the string in input box isn't change,click search button
###  the result isn't jump to 2018-12-25

**Comment by agreadname** [comment]
I am very rough to solve this problem
i add a props  
props：
 currentDaTe:{
        type:Boolean,
        default:true
  },
watch
 currentDaTe(val){
        var currentDay=moment(new Date(), 'YYYY-MM-DD')
        this.date = moment(currentDay, 'YYYY-MM-DD')
        this.lunarDate = moment(this.solar2lunar(this.date._d).day, 'YYYY-MM-DD')
        this.resetDayOfMonth()
        this.$emit('change', this.date, this.lunarDate, this.isLunar)
      }
father component 
@click="! currentDaTe"

**Comment by KimWooHyun** [comment]
That's good idea! 
I will fix it this week. Thanks for suggestion.
