### ISSUE TITLE
about localization to Chinese

### ISSUE THREAD

**Issue by kbdsbx** [KimWooHyun/vue-lunar-calendar#25]
This library is so interesting, but describe lunar in Chinese we are not write to "阴 1.20" or "阴 3.10" etc, in fact we used "正月二十" or "三月初十"

So Jan to Dec are 正月，二月，三月，四月，五月，六月，七月，八月，九月，十月，十一月，腊月

And 1st to 30th are 初一，初二，初三，初四，初五，初六，初七，初八，初九，初十，十一，十二，十三，十四，十五，十六，十七，十八，十九，二十，廿一，廿二，廿三，廿四，廿五，廿六，廿七，廿八，廿九，三十

**Comment by KimWooHyun** [comment]
@kbdsbx oh interesting! I did not know that.
but this library is korea lunar calendar.
so, It seems hard to modify. I'm so sorry.
Thank you for telling me.
