### ISSUE TITLE
Adding a new language

### ISSUE THREAD

**Issue by techguydev** [KimWooHyun/vue-lunar-calendar#7]
Hello Kim, thanks for the great component. 

What is the best way to add a different language that is not part of the component?

**Comment by KimWooHyun** [comment]
Hello, sorry to late.
First, thank you for your interest.

How to adding language.

# 1. Add to language after 26 line
`/src/lang.js`
```
,‘[country_name_short]’ : {
    'name': ‘[language_name]’,
    'days': [days_name_in_array],
    'solar': ‘[solar_name]’,
    'lunar': ‘[lunar_name]’,
    'leap' : ‘[leap_name]’,
    'solarShort': ‘[solar_name_short]’,
    'lunarShort': ‘[lunar_name_short]’
}
```

# 2. Add to select option after 11 line, 20 line
`/demo/App.vue`
```html
<option value="country_name_short">language_name</option>
```

# 3. Run script 
```
yarn build
yarn demo
```
if you run script `yarn start`

# 4. Write README.md
`README.md`
Add to language after 66 line

Thanks.
